# Generated by Django 6.0.1 on 2026-01-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="External ID to avoid duplicates (e.g. BienIci ID)",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("department_code", models.CharField(db_index=True, max_length=3)),
                ("postal_code", models.CharField(db_index=True, max_length=10)),
                ("city", models.CharField(db_index=True, max_length=128)),
                (
                    "annual_condominium_fees",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
